package visao;

import java.awt.event.ActionListener;


public class JanelaCadastro extends javax.swing.JDialog {
    
     
    public JanelaCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDescricaoProduto = new javax.swing.JTextArea();
        jLabelDescricaoProduto = new javax.swing.JLabel();
        jLabelNomeProduto = new javax.swing.JLabel();
        jTextNomeProduto = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jTextQuantidade = new javax.swing.JTextField();
        jTextValor = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jLabelQuantidade = new javax.swing.JLabel();
        jButtonCancelarCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCadastrar.setText("Cadastrar");

        jTextDescricaoProduto.setColumns(20);
        jTextDescricaoProduto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextDescricaoProduto.setRows(5);
        jTextDescricaoProduto.setToolTipText("Insira uma descrição para o produto");
        jTextDescricaoProduto.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextDescricaoProduto);

        jLabelDescricaoProduto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelDescricaoProduto.setText("Descrição");

        jLabelNomeProduto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelNomeProduto.setText("Nome");

        jTextNomeProduto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextNomeProduto.setToolTipText("Insira o nome do produto aqui");
        jTextNomeProduto.setName(""); // NOI18N

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setText("Cadastrar PRODUTO:");
        jLabelTitulo.setToolTipText("");

        jTextQuantidade.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextQuantidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextQuantidade.setToolTipText("Insira a quantidade do produto aqui");
        jTextQuantidade.setName(""); // NOI18N

        jTextValor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextValor.setToolTipText("Insira o valor do produto aqui");
        jTextValor.setName(""); // NOI18N

        jLabelValor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelValor.setText("Valor");

        jLabelQuantidade.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelQuantidade.setText("Quantidade");

        jButtonCancelarCadastro.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextValor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jTextNomeProduto))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarCadastro)
                    .addComponent(jButtonCadastrar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addBotaoCadastrarListener (ActionListener cal) {
	        jButtonCadastrar.addActionListener(cal);
    }
    
    public void addBotaoCancelarCadastroListener (ActionListener cal) {
	        jButtonCancelarCadastro.addActionListener(cal);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelarCadastro;
    private javax.swing.JLabel jLabelDescricaoProduto;
    private javax.swing.JLabel jLabelNomeProduto;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextDescricaoProduto;
    private javax.swing.JTextField jTextNomeProduto;
    private javax.swing.JTextField jTextQuantidade;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables
}
